services:
    controller:
        _exception_handler:
            class: \Veto\Debug\Controller\ExceptionController
            one_shot: true

    dispatcher:
        class: \Veto\MVC\Dispatcher
        parameters:
          - @container